name: localsearch
description: "Local E Commerce Platform"
version: 1.0.0+10
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  image_picker: ^1.0.7
  firebase_storage: ^12.1.3
  uuid: ^4.3.3
  feather_icons: ^1.2.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  speech_to_text: ^7.0.0
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.5
  shimmer: ^3.0.0
  video_player: ^2.8.6
  visibility_detector: ^0.4.0+2
  flick_video_player: ^0.9.0
  geolocator: ^13.0.1
  http: ^1.2.1
  carousel_slider: ^5.0.0
  intl: ^0.19.0 # to be decided
  image: ^4.2.0 #only used in one file
  # firebase_app_check: ^0.3.1+5
  # avatar_glow: ^3.0.1
  # connectivity_plus: ^6.0.4
  # youtube_player_flutter: ^9.0.3
  # firebase_messaging: ^15.0.4
  # flutter_local_notifications: ^17.1.2

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
  # flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - logo/logo.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
