Map<String, Map<String, List<String>>> householdSpecialCategories = {
  'Fashion & Clothing': {
    'Men Wear': [
      'Men Shirts',
      'Men T - Shirts',
      'Men Polos',
      'Men Trousers',
      'Men Jeans',
      'Men Night Wear',
      'Men Winter Wear',
      'Men Jackets',
      'Men Suits',
      'Men Active Wear',
      'Men Hats',
      'Men Scarves',
      'Men Belts',
      'Men Masks',
      'Men Gloves',
      'Men Tie',
      'Men Socks',
      'Men Foot Wear',
      'Men Formal Wear',
      'Men Party Wear',
      'Men Wedding Attire',
      'Men Coats',
      'Men Rain Wear',
      'Men Blazers',
      'Men Bottoms',
      'Men Kurta Pajama',
      'Men Sherwani',
      'Men Hoodies',
    ],
    'Accessories For Men': [
      'Men Scarves',
      'Men Masks',
      'Men Gloves',
      'Men Tie',
      'Men Hats',
      'Men Socks',
      'Men Belts',
      'Men Bags',
      'Men Wallets',
      'Men Watches',
    ],
    'Women Wear': [
      'Women Shirts',
      'Women T - Shirts',
      'Women Polos',
      'Women Trousers',
      'Women Saree',
      'Women Kurta Sets',
      'Women Ghagra Choli',
      'Women party Gowns',
      'Women Lehenga',
      'Women Punjabi Dress',
      'Women Dresses',
      'Women Night Wear',
      'Women Winter Wear',
      'Women Skirts',
      'Women Jackets',
      'Women Jeans',
      'Women Suits',
      'Women Active Wear',
      'Women Hats',
      'Women Scarves',
      'Women Belts',
      'Women Masks',
      'Women Gloves',
      'Women Tie',
      'Women Socks',
      'Women Foot Wear',
      'Women Formal Wear',
      'Women Party Wear',
      'Women Wedding Attire',
      'Women Coats',
      'Women Rain Wear',
      'Women Blazers',
    ],
    'Accessories For Women': [
      'Women Scarves',
      'Women Dupatta',
      'Women Masks',
      'Women Gloves',
      'Women Tie',
      'Women Hats',
      'Women Socks',
      'Women Belts',
      'Women Bags',
      'Women Purses',
      'Women Watches',
    ],
    'Kids Wear': [
      'Kids Shirts',
      'Kids T - Shirts',
      'Kids Polos',
      'Kids Trousers',
      'Kids Dresses',
      'Kids Night Wear',
      'Kids Winter Wear',
      'Kids Skirts',
      'Kids Jackets',
      'Kids Jeans',
      'Kids Suits',
      'Kids Active Wear',
      'Kids Hats',
      'Kids Scarves',
      'Kids Belts',
      'Kids Masks',
      'Kids Gloves',
      'Kids Tie',
      'Kids Socks',
      'Kids Foot Wear',
      'Kids Formal Wear',
      'Kids Party Wear',
      'Kids Wedding Attire',
      'Kids Coats',
      'Kids Rain Wear',
      'Kids Blazers',
    ],
    'Accessories For Kids': [
      'Scarves',
      'Masks',
      'Gloves',
      'Tie',
      'Hats',
      'Socks',
      'Belts',
      'Bags',
      'Wallets',
      'Watches',
      'Purses',
    ],
  },
  'Food': {
    'Daily Needs': [
      'Fruits',
      'Vegetables',
      'Milk & Other Dairy Products',
      'Grains',
      'Cereals',
      'Rice',
      'Beverages',
      'Condiments',
      'Ice Creams & Other Frozen Foods',
      'Juices & Shakes',
      'Spices',
      'Herbs',
      'Oils',
      'Nuts',
      'Seeds',
    ],
    'Ready To Eat Food': [
      'Baked Food',
      'Canned Food',
      'Packet Food',
      'Frozen Food',
      'Festive Special Food',
      'Indian Snacks',
      'Dry Snacks',
      'Roti & Sabji',
      'Thali',
      'Dal & Rice',
      'Gujarati Food',
      'Punjabi Food',
      'Rajasthani Food',
      'South Indian',
      'North Indian',
      'Sweets',
      'Cakes & Bakery Items',
      'Western',
      'Chinese',
    ],
    'Bakery Items': [
      'Bread',
      'Muffins',
      'Pizza Base',
      'Cookies',
      'Biscuits',
      'Cakes',
      'Pastries',
      'Donuts',
      'Brownies',
      'Cupcakes',
      'Buns',
    ],
    'Namkeen': [
      'Sev',
      'Mixture',
      'Chivda',
      'Murukku/Chakli',
      'Mathri',
      'Nimki/Namak Para',
      'Dal-based Snacks',
      'Peanuts',
      'Gathiya',
      'Boondi',
      'Other Namkeen',
      'Khakra',
      'Farsan',
      'Khatta Meetha Mix',
    ],
    'Street Food': [
      'Pani Puri/Golgappa',
      'Bhel Puri',
      'Pav Bhaji',
      'Vada Pav',
      'Dahi Puri',
      'Aloo Tikki',
      'Chole Bhature',
      'Sev Puri',
      'Dhokla',
      'Samosa',
      'Kachori',
      'Pav Bhaji',
      'Chaat',
      'Ragda Pattice',
      'Batata Vada',
      'Pav Bhaji',
      'Paneer Tikka',
      'Aloo Chaat',
      'Vegetable Pakora',
      'Chili Paneer',
      'Misal Pav',
      'Bhutte Ka Kees',
      'Vegetable Frankie/Kathi Roll',
      'Bajji/Bhajiya',
      'Vegetable Momos',
      'Dabeli',
      'Masala Dosa',
      'Idli',
      'Uttapam',
      'Mirchi Bajji',
    ],
    'Snacks': [],
    'Baked & Roasted Snacks': [],
    'Chaat': [],
    'Starters': [
      'Salads',
      'Papad',
      'Soups',
      'Raitas',
    ],
    'Main Course': [
      'Roti',
      'Paratha',
      'Dal',
      'Rice',
      'Pulav',
      'Biryani',
      'Gravy Sabji',
      'Non Gravy Sabji',
      'Thali',
    ],
    'Desserts': [],
    'Gujarati Food': [
      'Gujarati Breakfast',
      'Gujarati Snacks & Farsan',
      'Gujarati Main Course',
      'Gujarati Thali',
      'Gujarati Specials',
      'Gujarati Sweets & Desserts',
      'Gujarati Rice Dishes',
      'Gujarati Chutneys & Pickles',
    ],
    'Punjabi Food': [
      'Punjabi Breakfast',
      'Punjabi Snacks & Farsan',
      'Punjabi Main Course',
      'Punjabi Thali',
      'Punjabi Specials',
      'Punjabi Sweets & Desserts',
      'Punjabi Rice Dishes',
      'Punjabi Chutneys & Pickles',
    ],
    'Maharashtrian Food': [
      'Maharashtrian Breakfast',
      'Maharashtrian Snacks & Farsan',
      'Maharashtrian Main Course',
      'Maharashtrian Thali',
      'Maharashtrian Specials',
      'Maharashtrian Sweets & Desserts',
      'Maharashtrian Rice Dishes',
      'Maharashtrian Chutneys & Pickles',
    ],
    'South Indian Food': [
      'South Indian Breakfast',
      'South Indian Snacks & Farsan',
      'South Indian Main Course',
      'South Indian Thali',
      'South Indian Specials',
      'South Indian Sweets & Desserts',
      'South Indian Rice Dishes',
      'South Indian Chutneys & Pickles',
    ],
    'Chinese Food': [
      'Chinese Appetizers',
      'Chinese Soups',
      'Chinese Main Course',
      'Chinese Gravy Dishes',
      'Chinese Sides & Sauces',
    ],
    'Western Food': [
      'Western Starters',
      'Western Appetizers',
      'Western Soups',
      'Western Desserts',
      'Pastas',
      'Pizzas',
      'Tacos',
      'Burgers',
      'Sandwiches',
      'French Fries',
      'Wraps',
      'Sides',
      'Lasagna',
      'Western Sides & Sauces',
    ],
    'Sweets & Desserts': [
      'Ice Creams',
      'Chocolate',
      'Gulab Jamun',
      'Jalebi',
      'Rasgulla',
      'Kheer',
      'Ladoo',
      'Barfi',
      'Gajar ka Halwa',
      'Sandesh',
      'Cake',
      'Brownies',
      'Apple Pie',
      'Mousse',
      'Pudding',
    ],
    'Beverages': [
      'Tea',
      'Coffee',
      'Milk',
      'Water',
      'Smoothies',
      'Lemonade',
      'Green Tea',
      'Coconut Water',
      'Shakes',
      'Fruit Juice',
      'Vegetable Juice',
      'Almond Milk',
      'Soy Milk',
      'Cocktails',
      'Mocktails',
      'Hot Drinks',
      'Cold Drinks',
      'Energy Drinks',
      'Detox Drinks',
      'Soda',
      '',
      '',
    ],
  },
  'Beauty & Care': {
    'Face': [
      'Primer',
      'Foundation',
      'Concealer',
      'Setting Powder',
      'Contour Stick/Powder',
      'Blush',
      'Bronzer',
      'Highlighter',
      'Setting Spray',
      'BB Cream',
      'CC Cream',
      'Tinted Moisturizer',
    ],
    'Eyes': [
      'Eyeshadow Primer',
      'Eyeshadow Palettes',
      'Eyeliner',
      'Mascara',
      'Eyebrow Pencil',
      'Eyebrow Gel',
      'Eyebrow Powder',
      'False Eyelashes',
    ],
    'Lips': [
      'Lip Balm',
      'Lip Liner',
      'Matte Lipstick',
      'Glossy Lipstick',
      'Lipstick',
      'Lip Gloss',
    ],
    'Beard': [
      'Beard Filler',
      'Beard Balm/Oil',
    ],
    'Tools & Accessories': [
      'Combs',
      'Hair Ties',
      'Hair Clips',
      'Hair Bands',
      'Headbands',
      'Shower Cap',
      'Hair Scarves',
      'Makeup Remover',
      'Beauty Sponges',
      'Makeup Brush',
      'Styling Brush',
      'Eyelash Curler',
      'Tweezer',
      'Cotton Pads',
      'Brush Cleaner',
      'Blotting Paper',
      'Hair Dryer',
      'Curlings',
      'Towels',
      'Flat Iron',
      'Hair Rollers',
      'Hair Steamer',
      'Others',
    ],
    'Hair Care & Styling': [
      'Shampoo',
      'Conditioners',
      'Hair Oils',
      'Hair Serums',
      'Hair Masks',
      'Hair Wax',
      'Hair Creams',
      'Hair Vitamins & Supplements',
      'Styling Gel',
      'Styling Lotion',
      'Hair Tonics',
      'Scalp Treatment',
      'Protein Treatment',
      'Hair Growth Serum',
      'Mousses',
      'Hair Spray',
      'Shine Spray',
      'Hair Pomade',
      'Styling Foam',
      'Others',
    ],
    'Skin Care': [
      'Cleaner',
      'Toner',
      'Serum',
      'Moisturizer',
      'Creams',
      'Sunscreen',
      'Night Cream',
      'Anti-aging Cream',
      'Face Mask',
      'Sleeping Mask',
      'Aftershave Balm',
      'Beard Oil',
      'Facial Oil',
      'Pre-Shave Oil',
      'Face Scrub',
      'Hydrating Mist',
      'Exfoliator',
      'Pore Strips',
    ],
  },
  'Home Essentials': {
    'Cleaners': [
      'All Purpose Cleaner',
      'Glass Cleaner',
      'Bathroom Cleaner',
      'Kitchen Cleaner',
      'Floor Cleaner',
      'Carpet Cleaner',
      'Upholstery Cleaner',
      'Stainless Steel Cleaner',
      'Tile & Grout Cleaner',
      'Toilet Bowl Cleaner',
      'Oven Cleaner',
      'Drain Cleaner',
      'Hardwood Floor Cleaner',
      'Mold & Mildew Remover',
      'Stain Remover',
      'Disinfectant Spray',
      'Furniture Polish',
      'Dish Soap',
      'Laundry Detergent',
      'Fabric Softener',
    ],
    'Cleaning Tools': [
      'Broom',
      'Dustpan',
      'Mop',
      'Bucket',
      'Vacuum Cleaner',
      'Duster',
      'Microfiber Cloths',
      'Scrub Brush',
      'Sponge',
      'Squeengee',
      'Cleaning Gloves',
      'Lint Roller',
      'Toilet Brush',
      'Spray Bottle',
      'Cleaning Caddy',
      'Steam Cleaner',
      'Rubber Gloves',
      'Dust Mop',
      'Scouring Pad',
      'Cleaning Wipes',
    ],
  },
  'Health Care': {
    // ayurveda, homeopathy, personal care, sports supplements, diet & nutrition, health care devices, sports suppliments, offers and
    'Ayurvedic Products': [
      'Medicine',
      'Herbal Supplements',
      'Skincare',
      'Hair Care',
      'Massage Oils',
      'Teas',
      'Personal Care',
      'Digestive Aids',
      'Immune Boosters',
      'Joint Care',
      'Weight Management',
      'Dental Care',
      'Cosmetics',
      'Bath Products',
      'Essential Oils',
      'Health Tonics',
      'Herbal Extracts',
      'Stress Relief',
      'Anti-Aging Products',
      'Beauty Supplements',
    ],
  },
  'Jewelry': {
    // piercings, neck, face, hand, legs,
    '': [
      'Rings',
      'Necklaces',
      'Earrings',
      'Bracelets',
      'Anklets',
      'Brooches',
      'Pendants',
      'Chains',
      'Bangles',
      'Charms',
      'Jewelry Sets',
      'Men\'s Jewelry',
      'Women\'s Jewelry',
      'Children\'s Jewelry',
      'Fine Jewelry',
      'Fashion Jewelry',
      'Handmade Jewelry',
      'Wedding Jewelry',
      'Ethnic Jewelry',
      'Body Jewelry',
      'Custom Jewelry',
    ],
  },
  'Foot Wear': {},
  'Home Decor & Furnishing': {
    'Home Furnishing': [
      'Bed Sheets',
      // 'Mattress Covers'
      'Fitted Bed Sheets & Blinds',
      'Curtains',
      'Curtains Accessoriess',
      'Pillows',
      'Pillow Covers',
      'Cushions',
      'Cushion Covers',
      'Furniture Covers',
      'Kids Beddings',
      'Fabrics',
      'Carpets',
      'Table Liners',
      'Bath Liners',
      'Floor Mats',
      'Dohads',
      'Quilts',
      'Blankets',
      'Diwan Sets',
      'Mattress Protectors',
      'Orthopedic Products',
      'Gifting',
      'Others',
    ],
    'Home Decor': [
      'Table Top Decor',
      'Artificial Plants & Trees',
      'Artificial Flowers',
      'Vases',
      'Vase Fillers',
      'Planters',
      'Candles',
      'LED Candles',
      'Candle Holders',
      'Wall Decor',
      'Paintings',
      'Hangings',
      'Decorative Lights',
      'Figurines',
      'Show Pieces',
      'Wall Shelves',
      'Ethnic Wall Art',
      'Others',
    ],
    'Spiritual Decor': [
      'Idols',
      'Home Temples',
      'Spiritual Themed Lights',
      'Toran',
      'Stickers',
      'Others',
    ],
    'Lights': [
      'Decorative Lights',
      'String Lights',
      'Chandeliers',
      'Wall Lamps',
      'Pendant Lights',
      'Home Lamps',
      'Light Fixtures',
      'Night Lamps',
      'Outdoor Lights',
      'Garden Lights',
      'Bulbs',
      'Essential Lights',
      'Others',
    ],
  },
  'Art & Craft': {
    'Handcrafts': [
      'Pots',
      'Festive Handcrafts',
      'Woodwork',
      'Metalwork',
      'Threadwork',
      'Clothwork & Embroidery',
    ],
    'Art & Craft Supplies': [
      'Paper',
      'Crayons & Pastols',
      'Sketch Pen & Markers',
      'Drawing Books',
      'Scrap Books',
      'Paints & Brushes',
      'Canvas & Boards',
      'Glitters',
      'Adhesives & Glues',
      'Punches',
      'Threads & Wools',
      'Quillings',
      'Embossing',
      'Stencils',
      'Threads & Ribbon',
      'Card Making Kits',
      'Party Props & Supplies',
      'Gift Wrappings',
      'Knitting & Yarn Wools Essentials',
      'Beading & Jewelry Making Essentials',
      'Glue Guns',
      'Crafting Tools',
      'Others',
    ],
  },
  'Festive Essentials': {
    'Diwali': [
      'Decorative Lights',
      'String Lights',
      'Lanterns',
      'Holders',
      'Garlands',
      'Ornaments',
      'Christmas Trees',
      'Wreaths',
      'Tableware',
      'Party Decorations',
      'Gift Wrapping Supplies',
      'Holiday Cards',
      'Festive Clothing',
      'Seasonal Foods',
      'Fireworks',
      'Home Fragrances',
      'Holiday Music',
      'DIY Craft Kits',
      'Cultural Decorations',
      'Customized Gifts',
    ],
  }
};
