Map<String, Map<String, List<String>>> householdTypeCategorySubCategory = {
  'Fashion & Clothing': {
    'Men Wear': [
      'Men Shirts',
      'Men T - Shirts',
      'Men Polos',
      'Men Trousers',
      'Men Jeans',
      'Men Night Wear',
      'Men Winter Wear',
      'Men Jackets',
      'Men Suits',
      'Men Active Wear',
      'Men Hats',
      'Men Scarves',
      'Men Belts',
      'Men Masks',
      'Men Gloves',
      'Men Tie',
      'Men Socks',
      'Men Foot Wear',
      'Men Formal Wear',
      'Men Party Wear',
      'Men Wedding Attire',
      'Men Coats',
      'Men Rain Wear',
      'Men Blazers',
      'Men Bottoms',
      'Men Kurta Pajama',
      'Men Sherwani',
      'Men Hoodies',
      'Other Men Wear',
    ],
    'Accessories For Men': [
      'Men Scarves',
      'Men Masks',
      'Men Gloves',
      'Men Tie',
      'Men Hats',
      'Men Socks',
      'Men Belts',
      'Men Bags',
      'Men Wallets',
      'Men Watches',
      'Other Men Accessories',
    ],
    'Women Wear': [
      'Women Shirts',
      'Women T - Shirts',
      'Women Polos',
      'Women Trousers',
      'Women Saree',
      'Women Kurta Sets',
      'Women Ghagra Choli',
      'Women party Gowns',
      'Women Lehenga',
      'Women Punjabi Dress',
      'Women Dresses',
      'Women Night Wear',
      'Women Winter Wear',
      'Women Skirts',
      'Women Jackets',
      'Women Jeans',
      'Women Suits',
      'Women Active Wear',
      'Women Hats',
      'Women Scarves',
      'Women Belts',
      'Women Masks',
      'Women Gloves',
      'Women Tie',
      'Women Socks',
      'Women Foot Wear',
      'Women Formal Wear',
      'Women Party Wear',
      'Women Wedding Attire',
      'Women Coats',
      'Women Rain Wear',
      'Women Blazers',
      'Other Women Wear',
    ],
    'Accessories For Women': [
      'Women Scarves',
      'Women Dupatta',
      'Women Masks',
      'Women Gloves',
      'Women Tie',
      'Women Hats',
      'Women Socks',
      'Women Belts',
      'Women Bags',
      'Women Purses',
      'Women Watches',
      'Other Women Accessories',
    ],
    'Kids Wear': [
      'Kids Shirts',
      'Kids T - Shirts',
      'Kids Polos',
      'Kids Trousers',
      'Kids Dresses',
      'Kids Night Wear',
      'Kids Winter Wear',
      'Kids Skirts',
      'Kids Jackets',
      'Kids Jeans',
      'Kids Suits',
      'Kids Active Wear',
      'Kids Hats',
      'Kids Scarves',
      'Kids Belts',
      'Kids Masks',
      'Kids Gloves',
      'Kids Tie',
      'Kids Socks',
      'Kids Foot Wear',
      'Kids Formal Wear',
      'Kids Party Wear',
      'Kids Wedding Attire',
      'Kids Coats',
      'Kids Rain Wear',
      'Kids Blazers',
      'Other Kids Wear',
    ],
    'Accessories For Kids': [
      'Scarves',
      'Masks',
      'Gloves',
      'Tie',
      'Hats',
      'Socks',
      'Belts',
      'Bags',
      'Wallets',
      'Watches',
      'Purses',
      'Other Kids Accessories',
    ],
  },
  'Food': {
    'Daily Needs': [
      'Fruits',
      'Vegetables',
      'Milk & Other Dairy Products',
      'Grains',
      'Cereals',
      'Rice',
      'Beverages',
      'Condiments',
      'Ice Creams & Other Frozen Foods',
      'Juices & Shakes',
      'Spices',
      'Herbs',
      'Oils',
      'Nuts',
      'Seeds',
      'Other Daily Needs',
    ],
    'Ready To Eat Food': [
      'Baked Food',
      'Canned Food',
      'Packet Food',
      'Frozen Food',
      'Festive Special Food',
      'Indian Snacks',
      'Dry Snacks',
      'Roti & Sabji',
      'Thali',
      'Dal & Rice',
      'Gujarati Food',
      'Punjabi Food',
      'Rajasthani Food',
      'South Indian',
      'North Indian',
      'Sweets',
      'Cakes & Bakery Items',
      'Western',
      'Chinese',
      'Other Ready To Eat',
    ],
    'Bakery Items': [
      'Bread',
      'Muffins',
      'Pizza Base',
      'Cookies',
      'Biscuits',
      'Cakes',
      'Pastries',
      'Donuts',
      'Brownies',
      'Cupcakes',
      'Buns',
      'Other Bakery Items',
    ],
    'Namkeen': [
      'Sev',
      'Mixture',
      'Chivda',
      'Murukku/Chakli',
      'Mathri',
      'Nimki/Namak Para',
      'Dal-based Snacks',
      'Peanuts',
      'Gathiya',
      'Boondi',
      'Other Namkeen',
      'Khakra',
      'Farsan',
      'Khatta Meetha Mix',
      'Other Namkeen',
    ],
    'Snacks': [
      'Samosa',
      'Pakora (Bhajiya)',
      'Aloo Tikki',
      'Paneer Tikka',
      'Veg Cutlet',
      'Masala Vada',
      'Sabudana Vada',
      'Dhokla',
      'Khandvi',
      'Idli',
      'Medu Vada',
      'Vada Pav',
      'Batata Vada',
      'Methi na Gota',
      'Bread Pakora',
      'Hara Bhara Kabab',
      'Corn Fritters',
      'Chana Jor Garam',
      'Veg Spring Roll',
      'Pav Bhaji',
      'Bhel Puri',
      'Sev Puri',
      'Dabeli',
      'Pani Puri',
      'Ragda Pattice',
      'Moong Dal Chilla',
      'Chole Bhature',
      'Aloo Chaat',
      'Papdi Chaat',
      'Samosa Chaat',
      'Other Snacks',
    ],
    'Baked & Roasted Snacks': [
      'Roasted Chana',
      'Roasted Makhanas (Fox Nuts)',
      'Khakra',
      'Baked Mathri',
      'Baked Chakli',
      'Masala Peanuts (baked or roasted)',
      'Roasted Poha Chivda',
      'Bhel Mix (without sev)',
      'Baked Methi Crackers',
      'Baked Namak Pare',
      'Masala Papad (roasted)',
      'Baked Thepla Crackers',
      'Murmura (Puffed Rice)',
      'Chana Jor Garam (roasted)',
      'Baked Oats Chivda',
      'Roasted Bajra Puffs',
      'Roasted Moong Dal',
      'Baked Spiced Nuts',
      'Roasted Flax Seeds',
      'Roasted Pumpkin Seeds',
      'Baked Multigrain Chips',
      'Roasted Almonds with Spices',
      'Baked Ragi Chips',
      'Baked Beetroot Chips',
      'Roasted Cashews with Curry Leaves',
      'Spiced Murmura (Puffed Rice)',
      'Roasted Soy Nuts',
      'Baked Kale Chips (Indian Spices)',
      'Baked Vegetable Sticks',
      'Baked Lentil Cracker',
      'Other Baked & Roasted Snacks',
    ],
    'Chaat': [
      'Pani Puri (Golgappa)',
      'Bhel Puri',
      'Sev Puri',
      'Aloo Chaat',
      'Dahi Puri',
      'Pav Bhaji',
      'Ragda Pattice',
      'Papdi Chaat',
      'Samosa Chaat',
      'Dahi Bhalla',
      'Kachori Chaat',
      'Chole Bhature',
      'Aloo Tikki Chaat',
      'Pav Vada',
      'Masala Puri',
      'Dabeli',
      'Chana Chaat',
      'Moong Dal Chilla',
      'Raj Kachori',
      'Matar Kulcha',
      'Kutchi Dabeli',
      'Corn Chaat',
      'Fruit Chaat',
      'Churmuri',
      'Kanji Vada',
      'Tokri Chaat (Basket Chaat)',
      'Batata Vada',
      'Vada Pav',
      'Samosa Pav',
      'Khasta Kachori',
      'Misal Pav',
      'Dahi Papdi Chaat',
      'Bikaneri Bhujia',
      'Sabudana Vada',
      'Bread Pakora Chaat',
      'Methi na Gota (Methi Pakora) Chaat',
      'Roti Chaat',
      'Paneer Tikka Chaat',
      'Other Chaat',
    ],
    'Starters': [
      'Salads',
      'Papad',
      'Soups',
      'Raitas',
      'Other Starters',
    ],
    'Main Course': [
      'Roti',
      'Paratha',
      'Dal',
      'Rice',
      'Pulav',
      'Biryani',
      'Gravy Sabji',
      'Non Gravy Sabji',
      'Thali',
      'Other Main Course Items',
    ],
    'Gujarati Food': [
      'Gujarati Breakfast',
      'Gujarati Snacks & Farsan',
      'Gujarati Main Course',
      'Gujarati Thali',
      'Gujarati Specials',
      'Gujarati Sweets & Desserts',
      'Gujarati Rice Dishes',
      'Gujarati Chutneys & Pickles',
      'Other Gujarati Food',
    ],
    'Punjabi Food': [
      'Punjabi Breakfast',
      'Punjabi Snacks & Farsan',
      'Punjabi Main Course',
      'Punjabi Thali',
      'Punjabi Specials',
      'Punjabi Sweets & Desserts',
      'Punjabi Rice Dishes',
      'Punjabi Chutneys & Pickles',
      'Other Punjab Food',
    ],
    'Maharashtrian Food': [
      'Maharashtrian Breakfast',
      'Maharashtrian Snacks & Farsan',
      'Maharashtrian Main Course',
      'Maharashtrian Thali',
      'Maharashtrian Specials',
      'Maharashtrian Sweets & Desserts',
      'Maharashtrian Rice Dishes',
      'Maharashtrian Chutneys & Pickles',
      'Other Maharashtrian Food',
    ],
    'South Indian Food': [
      'South Indian Breakfast',
      'South Indian Snacks & Farsan',
      'South Indian Main Course',
      'South Indian Thali',
      'South Indian Specials',
      'South Indian Sweets & Desserts',
      'South Indian Rice Dishes',
      'South Indian Chutneys & Pickles',
      'Other South Indian Food',
    ],
    'Chinese Food': [
      'Chinese Appetizers',
      'Chinese Soups',
      'Chinese Main Course',
      'Chinese Gravy Dishes',
      'Chinese Sides & Sauces',
      'Other Chinese Food',
    ],
    'Western Food': [
      'Western Starters',
      'Western Appetizers',
      'Western Soups',
      'Western Desserts',
      'Pastas',
      'Pizzas',
      'Tacos',
      'Burgers',
      'Sandwiches',
      'French Fries',
      'Wraps',
      'Sides',
      'Lasagna',
      'Western Sides & Sauces',
      'Other Western Food',
    ],
    'Sweets & Desserts': [
      'Gulab Jamun',
      'Rasgulla',
      'Kaju Katli',
      'Jalebi',
      'Rasmalai',
      'Barfi',
      'Payasam',
      'Laddu',
      'Sooji Halwa',
      'Gajar ka Halwa',
      'Sandesh',
      'Peda',
      'Kheer',
      'Mysore Pak',
      'Mohanthal',
      'Khoya Burfi',
      'Basundi',
      'Shrikhand',
      'Malpua',
      'Chum Chum',
      'Petha',
      'Mishti Doi',
      'Rabri',
      'Chiroti',
      'Coconut Ladoo',
      'Malai Kofta',
      'Kalaadi',
      'Doodh Peda',
      'Khatta Meetha',
      'Anjeer Barfi',
      'Methi Thepla',
      'Suji Ka Halwa',
      'Gulkand',
      'Saffron Peda',
      'Thandai',
      'Bhapa Doi',
      'Rawa Kesari',
      'Doodhi Halwa',
      'Moong Dal Halwa',
      'Aloo Halwa',
      'Other Sweets & Desserts',
    ],
    'Beverages': [
      'Masala Chai',
      'Lassi',
      'Mango Lassi',
      'Buttermilk (Chaas)',
      'Coconut Water',
      'Jaljeera',
      'Aam Panna',
      'Falooda',
      'Thandai',
      'Nimbu Pani (Lemonade)',
      'Sugarcane Juice',
      'Badam Milk',
      'Rose Milk',
      'Sharbat',
      'Filter Coffee',
      'Sattu Drink',
      'Banana Smoothie',
      'Kokum Sherbet',
      'Solkadhi',
      'Apple Ginger Juice',
      'Pomegranate Juice',
      'Carrot and Beetroot Juice',
      'Kesar Milk',
      'Tulsi Tea',
      'Green Tea',
      'Almond Milkshake',
      'Dates Milkshake',
      'Ginger Lemon Tea',
      'Herbal Tea',
      'Mint Lemonade',
      'Turmeric Milk (Golden Milk)',
      'Watermelon Juice',
      'Pineapple Juice',
      'Amla Juice',
      'Cucumber Cooler',
      'Masala Soda',
      'Fennel Seed Drink (Saunf Sharbat)',
      'Hibiscus Tea',
      'Jaggery Water (Gur Sharbat)',
      'Bael Sharbat',
      'Other Beverages',
    ],
  },
  'Beauty & Care': {
    'Face': [
      'Primer',
      'Foundation',
      'Concealer',
      'Setting Powder',
      'Contour Stick/Powder',
      'Blush',
      'Bronzer',
      'Highlighter',
      'Setting Spray',
      'BB Cream',
      'CC Cream',
      'Tinted Moisturizer',
      'Other Face Beauty & Face Items',
    ],
    'Eyes': [
      'Eyeshadow Primer',
      'Eyeshadow Palettes',
      'Eyeliner',
      'Mascara',
      'Eyebrow Pencil',
      'Eyebrow Gel',
      'Eyebrow Powder',
      'False Eyelashes',
      'Other Eye Beauty & Care Items',
    ],
    'Lips': [
      'Lip Balm',
      'Lip Liner',
      'Matte Lipstick',
      'Glossy Lipstick',
      'Lipstick',
      'Lip Gloss',
      'Other Lip Beauty & Care Items',
    ],
    'Beard': [
      'Beard Filler',
      'Beard Balm/Oil',
      'Other Beard Beauty & Care Items',
    ],
    'Tools & Accessories': [
      'Combs',
      'Hair Ties',
      'Hair Clips',
      'Hair Bands',
      'Headbands',
      'Shower Cap',
      'Hair Scarves',
      'Makeup Remover',
      'Beauty Sponges',
      'Makeup Brush',
      'Styling Brush',
      'Eyelash Curler',
      'Tweezer',
      'Cotton Pads',
      'Brush Cleaner',
      'Blotting Paper',
      'Hair Dryer',
      'Curlings',
      'Towels',
      'Flat Iron',
      'Hair Rollers',
      'Hair Steamer',
      'Other Tools',
    ],
    'Hair Care & Styling': [
      'Shampoo',
      'Conditioners',
      'Hair Oils',
      'Hair Serums',
      'Hair Masks',
      'Hair Wax',
      'Hair Creams',
      'Hair Vitamins & Supplements',
      'Styling Gel',
      'Styling Lotion',
      'Hair Tonics',
      'Scalp Treatment',
      'Protein Treatment',
      'Hair Growth Serum',
      'Mousses',
      'Hair Spray',
      'Shine Spray',
      'Hair Pomade',
      'Styling Foam',
      'Other Hair Care & Styling Products',
    ],
    'Skin Care': [
      'Cleaner',
      'Toner',
      'Serum',
      'Moisturizer',
      'Creams',
      'Sunscreen',
      'Night Cream',
      'Anti-aging Cream',
      'Face Mask',
      'Sleeping Mask',
      'Aftershave Balm',
      'Beard Oil',
      'Facial Oil',
      'Pre-Shave Oil',
      'Face Scrub',
      'Hydrating Mist',
      'Exfoliator',
      'Pore Strips',
      'Other Skin Care Products'
    ],
  },
  'Home Essentials': {
    'Cleaners': [
      'All Purpose Cleaner',
      'Glass Cleaner',
      'Bathroom Cleaner',
      'Kitchen Cleaner',
      'Floor Cleaner',
      'Carpet Cleaner',
      'Upholstery Cleaner',
      'Stainless Steel Cleaner',
      'Tile & Grout Cleaner',
      'Toilet Bowl Cleaner',
      'Oven Cleaner',
      'Drain Cleaner',
      'Hardwood Floor Cleaner',
      'Mold & Mildew Remover',
      'Stain Remover',
      'Disinfectant Spray',
      'Furniture Polish',
      'Dish Soap',
      'Laundry Detergent',
      'Fabric Softener',
      'Other Cleaners',
    ],
    'Cleaning Tools': [
      'Broom',
      'Dustpan',
      'Mop',
      'Bucket',
      'Vacuum Cleaner',
      'Duster',
      'Microfiber Cloths',
      'Scrub Brush',
      'Sponge',
      'Squeengee',
      'Cleaning Gloves',
      'Lint Roller',
      'Toilet Brush',
      'Spray Bottle',
      'Cleaning Caddy',
      'Steam Cleaner',
      'Rubber Gloves',
      'Dust Mop',
      'Scouring Pad',
      'Cleaning Wipes',
      'Other Tools',
    ],
  },
  'Health Care': {
    'Ayurvedic Products': [
      'Chyawanprash',
      'Herbal Supplements',
      'Herbal Teas',
      'Herbal Powders',
      'Ayurvedic Oils',
      'Tablets and Capsules',
      'Juices',
      'Face Packs',
      'Detox Products',
      'Nasal Drops',
      'Tonics',
      'Syrups',
      'Balms',
      'Herbal Ghee',
      'Digestive Aids',
      'Herbal Extracts',
      'Creams and Lotions',
      'Oral Health Products',
      'Hair Care Products',
      'Body Scrubs',
      'Bath Powders',
      'Massage Oils',
      'Immunity Boosters',
      'Sleep Aids',
      'Energy Supplements',
      'Menstrual Health Products',
      'Joint Care Supplements',
      'Weight Management Products',
      'Skin Care Oil',
      'Other Ayurvedic Products',
    ],
    'Homeopathy': [
      'Mother Tinctures',
      'Tablets',
      'Pellets',
      'Syrups',
      'Ointments',
      'Drops',
      'Powders',
      'Nasal Drops',
      'Oral Solutions',
      'Creams',
      'Gels',
      'Pastes',
      'Immune Products',
      'Herbal Products',
      'Cough Syrups',
      'Allergy Products',
      'Digestive Aids',
      'Skin Care Products',
      'Pain Relief Products',
      'Sleep Aids',
      'Hormonal Balance Products',
      'Eye Care Products',
      'Ear Care Products',
      'Dental Care Products',
      'Women\'s Products',
      'Other Homeopathy Products',
    ],
    'Personal Care': [
      'Cleansers',
      'Moisturizers',
      'Shampoos',
      'Conditioners',
      'Body Washes',
      'Scrubs',
      'Face Masks',
      'Lip Balms',
      'Sunscreens',
      'Hair Oils',
      'Deodorants',
      'Hand Creams',
      'Foot Creams',
      'Toothpastes',
      'Body Lotions',
      'Facial Serums',
      'Toners',
      'Exfoliators',
      'Hair Masks',
      'Body Butters',
      'Bath Salts',
      'Anti-aging Creams',
      'Eye Creams',
      'Shaving Creams',
      'Beard Oils',
      'Body Sprays',
      'Nail Care Products',
      'Hair Styling Products',
      'Makeup Removers',
      'Hand Sanitizers',
      'Other Personal Care Products',
    ],
    'Sports Suplemments': [
      'Protein Powders',
      'Amino Acids',
      'BCAA (Branched-Chain Amino Acids)',
      'Pre-Workout Supplements',
      'Post-Workout Recovery',
      'Creatine',
      'Multivitamins',
      'Electrolyte Powders',
      'Energy Bars',
      'Sports Drinks',
      'Omega-3 Supplements',
      'Glutamine',
      'Casein Protein',
      'Plant-Based Protein Blends',
      'Joint Support Supplements',
      'Performance Enhancers',
      'Adaptogens',
      'Fat Burners',
      'Herbal Recovery Aids',
      'Hydration Tablets',
      'Recovery Drinks',
      'Vegan BCAA',
      'Vegan Creatine',
      'Superfood Powders',
      'Collagen Supplements',
      'Immune Support Supplements',
      'Antioxidant Supplements',
      'Natural Test Boosters',
      'Caffeine Supplements',
      'Electrolyte Tablets',
      'Other Sports Supplements',
    ],
    'Diet & Nutrition': [
      'Protein Powders',
      'Meal Replacement Shakes',
      'Nutritional Bars',
      'Multivitamins',
      'Omega-3 Supplements',
      'Fiber Supplements',
      'Probiotics',
      'Superfood Powders',
      'Green Tea Extracts',
      'Herbal Supplements',
      'Energy Drinks',
      'Amino Acids',
      'Vitamin D Supplements',
      'Iron Supplements',
      'Calcium Supplements',
      'Collagen Supplements',
      'Antioxidant Supplements',
      'Herbal Teas',
      'Adaptogens',
      'Detox Powders',
      'Sports Supplements',
      'Weight Management Supplements',
      'Electrolyte Supplements',
      'Digestive Enzymes',
      'Vegan Omega-3',
      'Plant-Based Meal Additives',
      'Supergreens Powders',
      'Energy Tablets',
      'Vitamin B12 Supplements',
      'Antioxidant Capsules',
      'Other Diet & Nutrition Products',
    ],
    'Health Care Devices': [
      'Blood Pressure Monitors',
      'Glucometers',
      'Digital Thermometers',
      'Pulse Oximeters',
      'Weighing Scales',
      'Nebulizers',
      'Fitness Trackers',
      'ECG Monitors',
      'Blood Glucose Meters',
      'Hearing Aids',
      'Sleep Apnea Devices',
      'Blood Oxygen Monitors',
      'Infrared Thermometers',
      'Personal ECG Devices',
      'Home Care Nebulizers',
      'Body Fat Scales',
      'Smartwatches with Health Tracking',
      'Respiratory Inhalers',
      'Digital Stethoscopes',
      'Temperature Sensors',
      'Home ECG Monitors',
      'Activity Monitors',
      'Body Composition Analyzers',
      'Pulse Massagers',
      'Infrared Heat Therapy Devices',
      'Personal Blood Pressure Monitors',
      'Automated External Defibrillators (AEDs)',
      'Smart Glucose Monitors',
      'Oxygen Concentrators',
      'Wearable Health Monitor',
      'Other Health Care Devices',
    ],
  },
  'Jewelry': {
    'Neck': [
      'Necklace',
      'Pearl Necklace',
      'Choker',
      'Pendant Set',
      'Mangalsutra',
      'Tika',
      'Chain',
      'Collar',
      'Rani Haar',
      'Satlada',
      'Locket',
      'Choker Set',
      'Traditional Necklace',
      'Modern Necklace',
      'Multi-layered Necklace',
      'Other Neck Jewelry',
    ],
    'Legs': [
      'Payal',
      'Bichiya',
      'Ghungroo',
      'Toe Rings',
      'Toe Anklets',
      'Other Legs Jewelry',
    ],
    'Hands': [
      'Bangles',
      'Bracelets',
      'Kadas',
      'Chuda',
      'Rakhdi',
      'Kangan',
      'Armlets',
      'Hathphool',
      'Kada Bangles',
      'Traditional Bangles',
      'Other Hands Jewelry',
    ],
    'Face': [
      'Naths',
      'Nose Pins',
      'Nose Rings',
      'Maang Tikka',
      'Bindi',
      'Earring Tops',
      'Eye Brooch',
      'Tikka',
      'Jhumar',
      'Nose Chain',
      'Hair Accessories',
      'Other Face Jewelry',
    ],
  },
  'Foot Wear': {
    'Men': [
      'Men Sneakers',
      'Men Loafers',
      'Men Boots',
      'Men Sandals',
      'Men Oxfords',
      'Men Ballet Flats',
      'Men Moccasins',
      'Men Wedges',
      'Men High Heels',
      'Men Brogues',
      'Men Derby Shoes',
      'Men Espadrilles',
      'Men Slip-Ons',
      'Men Running Shoes',
      'Men Hiking Boots',
      'Men Ankle Boots',
      'Men Chelsea Boots',
      'Men Dress Boots',
      'Men Clogs',
      'Men Mules',
      'Other Men Footwear',
    ],
    'Women': [
      'Women Sneakers',
      'Women Loafers',
      'Women Boots',
      'Women Sandals',
      'Women Oxfords',
      'Women Ballet Flats',
      'Women Moccasins',
      'Women Wedges',
      'Women High Heels',
      'Women Brogues',
      'Women Derby Shoes',
      'Women Espadrilles',
      'Women Slip-Ons',
      'Women Running Shoes',
      'Women Hiking Boots',
      'Women Ankle Boots',
      'Women Chelsea Boots',
      'Women Dress Boots',
      'Women Clogs',
      'Women Mules',
      'Other Women Footwear',
    ],
    'Kids': [
      'Kids Sneakers',
      'Kids Loafers',
      'Kids Boots',
      'Kids Sandals',
      'Kids Oxfords',
      'Kids Ballet Flats',
      'Kids Moccasins',
      'Kids Wedges',
      'Kids High Heels',
      'Kids Brogues',
      'Kids Derby Shoes',
      'Kids Espadrilles',
      'Kids Slip-Ons',
      'Kids Running Shoes',
      'Kids Hiking Boots',
      'Kids Ankle Boots',
      'Kids Chelsea Boots',
      'Kids Dress Boots',
      'Kids Clogs',
      'Kids Mules',
      'Other Kids Footwear',
    ],
  },
  'Home Decor & Furnishing': {
    'Home Furnishing': [
      'Bed Sheets',
      // 'Mattress Covers'
      'Fitted Bed Sheets & Blinds',
      'Curtains',
      'Curtains Accessoriess',
      'Pillows',
      'Pillow Covers',
      'Cushions',
      'Cushion Covers',
      'Furniture Covers',
      'Kids Beddings',
      'Fabrics',
      'Carpets',
      'Table Liners',
      'Bath Liners',
      'Floor Mats',
      'Dohads',
      'Quilts',
      'Blankets',
      'Diwan Sets',
      'Mattress Protectors',
      'Orthopedic Products',
      'Gifting',
      'Other Home Furnishing Products',
    ],
    'Home Decor': [
      'Table Top Decor',
      'Artificial Plants & Trees',
      'Artificial Flowers',
      'Vases',
      'Vase Fillers',
      'Planters',
      'Candles',
      'LED Candles',
      'Candle Holders',
      'Wall Decor',
      'Paintings',
      'Hangings',
      'Decorative Lights',
      'Figurines',
      'Show Pieces',
      'Wall Shelves',
      'Ethnic Wall Art',
      'Other Home Decor Products',
    ],
    'Spiritual Decor': [
      'Idols',
      'Home Temples',
      'Spiritual Themed Lights',
      'Toran',
      'Stickers',
      'Other Spiritual Decor Products',
    ],
    'Lights': [
      'Decorative Lights',
      'String Lights',
      'Chandeliers',
      'Wall Lamps',
      'Pendant Lights',
      'Home Lamps',
      'Light Fixtures',
      'Night Lamps',
      'Outdoor Lights',
      'Garden Lights',
      'Bulbs',
      'Essential Lights',
      'Other Lights',
    ],
  },
  'Art & Craft': {
    'Handcrafts': [
      'Pots',
      'Festive Handcrafts',
      'Woodwork',
      'Metalwork',
      'Threadwork',
      'Clothwork & Embroidery',
      'Other Handcrafts',
    ],
    'Art & Craft Supplies': [
      'Paper',
      'Crayons & Pastols',
      'Sketch Pen & Markers',
      'Drawing Books',
      'Scrap Books',
      'Paints & Brushes',
      'Canvas & Boards',
      'Glitters',
      'Adhesives & Glues',
      'Punches',
      'Threads & Wools',
      'Quillings',
      'Embossing',
      'Stencils',
      'Threads & Ribbon',
      'Card Making Kits',
      'Party Props & Supplies',
      'Gift Wrappings',
      'Knitting & Yarn Wools Essentials',
      'Beading & Jewelry Making Essentials',
      'Glue Guns',
      'Crafting Tools',
      'Other Art & Craft Supplies',
    ],
  },
  'Festive Essentials': {
    'Decorations': [
      'Rangoli colors',
      'Diyas (oil lamps)',
      'Torans (door hangings)',
      'Fairy lights',
      'Festive lanterns',
      'Decorative candles',
      'Festive tableware',
      'Wall hangings',
      'Flower garlands',
      'Paper decorations',
      'Puja Essentials',
      'Incense sticks',
      'Puja thali',
      'Camphor',
      'Kumkum',
      'Flowers',
      'Bells',
      'Holy books',
      'Sacred threads',
      'Conch shells',
      'Puja idols',
      'Gifts',
      'Dry fruit boxes',
      'Silver coins',
      'Gift hampers',
      'Cash envelopes',
      'Perfumes',
      'Home decor items',
      'Personalized gifts',
      'Gift cards',
      'Handicrafts',
      'Photo frames',
      'Miscellaneous',
      'Firecrackers',
      'Greeting cards',
      'Traditional music instruments',
      'Festive wrapping paper',
      'Seasonal plants',
      'Festive masks',
      'Henna (mehndi)',
      'Decorative baskets',
      'Umbrellas',
      'Cultural artifacts',
      'Marigold strings',
      'Decorative bells',
      'Tapestries',
      'Festive curtains',
      'Table runners',
      'Door beads',
      'Festive wall decals',
      'String lights with shapes',
      'Decorative plates',
      'Crystal hangings',
      'Other Decorations',
    ],
    'Puja Essentials': [
      'Clothing For Gods',
      'Incense sticks (Dhoop Agarbati)',
      'God Photos',
      'Puja thali',
      'Camphor',
      'Kumkum',
      'Flowers',
      'Bells',
      'Haldi Kumkum Karanda (Plate)',
      'Holy books',
      'Sacred threads (Moli)',
      'Conch shells',
      'Puja idols',
      'Brass lamps (Diya)',
      'Holy Containers (Puja Bartan)',
      'Sandalwood',
      'Kalash (Water Vessel)',
      'Ghee lamps',
      'Ritual conch (shankha)',
      'Puja mats',
      'Other Puja Essentials',
    ],
    'Gifts': [
      'Dry fruit boxes',
      'Silver coins',
      'Gift hampers',
      'Cash envelopes',
      'Perfumes',
      'Home decor items',
      'Personalized gifts',
      'Gift cards',
      'Handicrafts',
      'Photo frames',
      'Art prints',
      'Scented candles',
      'Spiritual books',
      'Customized jewelry boxes',
      'Traditional games',
      'Handmade soaps',
      'Aroma diffusers',
      'Meditation cushions',
      'Artistic pottery',
      'Other Gifts',
    ],
    'Miscellaneous': [
      'Firecrackers',
      'Greeting cards',
      'Traditional music instruments',
      'Festive wrapping paper',
      'Seasonal plants',
      'Festive masks',
      'Henna (mehndi)',
      'Decorative baskets',
      'Umbrellas',
      'Cultural artifacts',
      'Traditional puppets',
      'Ethnic dolls',
      'Decorative fans',
      'Cultural DVDs',
      'Traditional board games',
      'Storytelling books',
      'Ethnic musical CDs',
      'Cultural dance props',
      'Traditional masks',
      'Decorative umbrellas',
      'Other Miscellaneous Products',
    ],
    'Specific Festive Essentials': [
      'Diwali Essentials',
      'Holi Essentials',
      'Navratri Essentials',
      'Christmas Essentials',
      'Eid Essentials',
      'Baisakhi Essentials',
      'Makar Sankranti Essentials',
      'New Year Essentials',
      'Lohri Essentials',
      'Jain Festival Essentials',
      'Durga Puja Essentials',
      'Dussehra Essentials',
      'Ganesh Chaturthi Essentials',
      'Raksha Bandhan Essentials',
      'Pongal Essentials',
      'Onam Essentials',
      'Gudi Padwa Essentials',
      'Other Specific Festive Products',
    ],
  }
};
