Map<String, Map<String, List<String>>> servicesMap = {
  'Home': {
    'Household Services': [
      'Cleaning Services',
      'Laundry Services',
      'Grocery Shopping',
      'Meal Preparation',
      'Home Organization',
    ],
    'Maintenance And Repair': [
      'Appliance Repair',
      'Plumbing Services',
      'Electrical Services',
      'Carpentry Services',
      'Painting Services',
    ],
    'Interior Decoration': [
      'Furniture Assembly',
      'Wardrobe Organization',
      'Interior Painting',
    ],
    'Home Improvement': [
      'Kitchen Remodeling',
      'Bathroom Remodeling',
      'Flooring Installation',
      'Exterior Maintenance',
    ],
    'Outdoor Services': [
      'Gardening Services',
      'Landscaping Design',
      'Patio Maintenance',
    ],
  },
  'Office': {
    'Cleaning Services': [
      'Office Cleaning',
      'Janitorial Services',
      'Deep Cleaning',
      'Surface Sanitization',
    ],
    'Technical Support': [
      'IT Support',
      'Computer Repair',
      'Network Setup',
      'Software Installation',
      'Printer Maintenance',
    ],
    'Facilities Management': [
      'HVAC Maintenance',
      'Security Services',
      'Building Maintenance',
      'Waste Management',
    ],
    'Administrative Support': [
      'Document Management',
      'Appointment Scheduling',
      'Meeting Coordination',
      'Mail Handling',
      'Office Supplies Management',
    ],
    'Tech Setup And Maintenance': [
      'AV Equipment Setup',
      'Phone System Setup',
      'Server Maintenance',
      'Cabling And Wiring',
      'Data Backup',
    ],
  },
  'Retail Stores': {
    'Customer Service': [
      'Customer Enquiries',
      'Returns Processing',
      'Checkout Assistance',
      'Product Recommendations',
      'Gift Wrapping',
    ],
    'Merchandising': [
      'Product Display Setup',
      'Inventory Management',
      'Visual Merchandising',
      'Price Labeling',
    ],
    'Stock Management': [
      'Stock Replenishment',
      'Inventory Audits',
      'Shipment Receiving',
      'Stockroom Organization',
    ],
    'Checkout Operations': [
      'Cashier Services',
      'Barcode Scanning',
      'Bagging Assistance',
      'Payment Processing',
    ],
    'Store Maintenance': [
      'Fixture Repair',
      'Cleaning Services',
      'Lighting Maintenance',
      'Exterior Maintenance',
      'Security System Monitoring',
    ],
  },
  'Restaurant': {
    'Kitchen Operations': [
      'Food Preparation',
      'Dishwashing',
      'Cooking Assistance',
      'Ingredient Preparation',
    ],
    'Table Service': [
      'Table Setup',
      'Order Taking',
      'Food Serving',
      'Table Clearing',
    ],
    'Bar Services': [
      'Drink Mixing',
      'Bar Setup',
      'Bartending Services',
      'Bar Cleaning',
    ],
    'Outdoor Maintenance': [
      'Patio Setup',
      'Garden Maintenance',
      'Exterior Cleaning',
      'Outdoor Seating Arrangement',
    ],
    'Restroom Services': [
      'Restocking Supplies',
      'Restroom Maintenance',
      'Handicap Assistance',
    ],
  },
  'Educational Institutes': {
    'Educational Support': [
      'Classroom Setup',
      'Teaching Assistance',
      'Student Tutoring',
      'Educational Materials Preparation',
      'Attendance Tracking',
    ],
    'Library Services': [
      'Book Cataloging',
      'Shelving And Organization',
      'Book Repair',
    ],
    'Playground Management': [
      'Play Equipment Inspection',
      'Safety Monitoring',
      'Playground Cleaning',
      'Equipment Repair',
    ],
    'Cafeteria Operations': [
      'Food Preparation',
      'Meal Service',
      'Dining Area Cleaning',
      'Menu Planning',
    ],
    'Teachers': [
      'English Teacher',
      'Mathematics Teacher',
      'Science Teacher',
      'History Teacher',
    ],
  },
  'Hospital': {
    'Patient Care': [
      'Patient Assistance',
      'Bedside Monitoring',
      'Patient Comfort Services',
      'Medical Equipment Setup',
    ],
    'Emergency Services': [
      'Triage Coordination',
      'Emergency Care Assistance',
      'Emergency Equipment Setup',
      'Patient Transport',
    ],
    'Surgical Services': [
      'Operating Theater Setup',
      'Surgical Assistance',
      'Instrument Sterilization',
      'Patient Preparation',
    ],
    'Administrative Support': [
      'Patient Check-in/out',
      'Appointment Scheduling',
      'Visitor Assistance',
      'Medical Records Management',
    ],
    'Laboratory Services': [
      'Sample Collection',
      'Test Analysis',
      'Lab Equipment Maintenance',
      'Data Entry',
    ],
  },
  'Gym': {
    'Fitness Training': [
      'Personal Training',
      'Group Fitness Classes',
      'Fitness Assessments',
      'Workout Planning',
    ],
    'Equipment Maintenance': [
      'Equipment Setup',
      'Equipment Cleaning',
      'Equipment Repair',
      'Maintenance Checks',
    ],
    'Customer Assistance': [
      'Membership Enquiries',
      'Fitness Consultations',
      'Payment Processing',
      'Gym Orientation',
    ],
    'Facility Management': [
      'Facility Cleaning',
      'Locker Management',
      'Shower Maintenance',
      'Safety Monitoring',
    ],
    'Administrative Support': [
      'Appointment Scheduling',
      'Record Keeping',
      'Billing Assistance',
      'Inventory Management',
    ],
  },
};
