Map<String, Map<String, List<String>>> servicesMap = {
  'Home': {
    'Household Services': [
      'Cleaning services',
      'Laundry services',
      'Grocery shopping',
      'Meal preparation',
      'Home organization',
    ],
    'Maintenance and Repair': [
      'Appliance repair',
      'Plumbing services',
      'Electrical services',
      'Carpentry services',
      'Painting services',
    ],
    'Interior Decoration': [
      'Furniture assembly',
      'Wardrobe organization',
      'Interior painting',
    ],
    'Home Improvement': [
      'Kitchen remodeling',
      'Bathroom remodeling',
      'Flooring installation',
      'Exterior maintenance',
    ],
    'Outdoor Services': [
      'Gardening services',
      'Landscaping design',
      'Patio maintenance',
    ],
  },
  'Office': {
    'Cleaning Services': [
      'Office cleaning',
      'Janitorial services',
      'Deep cleaning',
      'Surface sanitization',
    ],
    'Technical Support': [
      'IT support',
      'Computer repair',
      'Network setup',
      'Software installation',
      'Printer maintenance',
    ],
    'Facilities Management': [
      'HVAC maintenance',
      'Security services',
      'Building maintenance',
      'Waste management',
    ],
    'Administrative Support': [
      'Document management',
      'Appointment scheduling',
      'Meeting coordination',
      'Mail handling',
      'Office supplies management',
    ],
    'Tech Setup and Maintenance': [
      'AV equipment setup',
      'Phone system setup',
      'Server maintenance',
      'Cabling and wiring',
      'Data backup',
    ],
  },
  'Retail Stores': {
    'Customer Service': [
      'Customer Enquiries',
      'Returns processing',
      'Checkout assistance',
      'Product recommendations',
      'Gift wrapping',
    ],
    'Merchandising': [
      'Product display setup',
      'Inventory management',
      'Visual merchandising',
      'Price labeling',
    ],
    'Stock Management': [
      'Stock replenishment',
      'Inventory audits',
      'Shipment receiving',
      'Stockroom organization',
    ],
    'Checkout Operations': [
      'Cashier services',
      'Barcode scanning',
      'Bagging assistance',
      'Payment processing',
    ],
    'Store Maintenance': [
      'Fixture repair',
      'Cleaning services',
      'Lighting maintenance',
      'Exterior maintenance',
      'Security system monitoring',
    ],
  },
  'Restaurant': {
    'Kitchen Operations': [
      'Food preparation',
      'Dishwashing',
      'Cooking assistance',
      'Ingredient preparation',
    ],
    'Table Service': [
      'Table setup',
      'Order taking',
      'Food serving',
      'Table clearing',
    ],
    'Bar Services': [
      'Drink mixing',
      'Bar setup',
      'Bartending services',
      'Bar cleaning',
    ],
    'Outdoor Maintenance': [
      'Patio setup',
      'Garden maintenance',
      'Exterior cleaning',
      'Outdoor seating arrangement',
    ],
    'Restroom Services': [
      'Restocking supplies',
      'Restroom maintenance',
      'Handicap assistance',
    ],
  },
  'Educational Institutes': {
    'Educational Support': [
      'Classroom setup',
      'Teaching assistance',
      'Student tutoring',
      'Educational materials preparation',
      'Attendance tracking',
    ],
    'Library Services': [
      'Book cataloging',
      'Shelving and organization',
      'Book repair',
    ],
    'Playground Management': [
      'Play equipment inspection',
      'Safety monitoring',
      'Playground cleaning',
      'Equipment repair',
    ],
    'Cafeteria Operations': [
      'Food preparation',
      'Meal service',
      'Dining area cleaning',
      'Menu planning',
    ],
    'Teachers': [
      'English teacher',
      'Mathematics teacher',
      'Science teacher',
      'History teacher',
    ],
  },
  'Hospital': {
    'Patient Care': [
      'Patient assistance',
      'Bedside monitoring',
      'Patient comfort services',
      'Medical equipment setup',
    ],
    'Emergency Services': [
      'Triage coordination',
      'Emergency care assistance',
      'Emergency equipment setup',
      'Patient transport',
    ],
    'Surgical Services': [
      'Operating theater setup',
      'Surgical assistance',
      'Instrument sterilization',
      'Patient preparation',
    ],
    'Administrative Support': [
      'Patient check-in/out',
      'Appointment scheduling',
      'Visitor assistance',
      'Medical records management',
    ],
    'Laboratory Services': [
      'Sample collection',
      'Test analysis',
      'Lab equipment maintenance',
      'Data entry',
    ],
  },
  'Gym': {
    'Fitness Training': [
      'Personal training',
      'Group fitness classes',
      'Fitness assessments',
      'Workout planning',
    ],
    'Equipment Maintenance': [
      'Equipment setup',
      'Equipment cleaning',
      'Equipment repair',
      'Maintenance checks',
    ],
    'Customer Assistance': [
      'Membership Enquiries',
      'Fitness consultations',
      'Payment processing',
      'Gym orientation',
    ],
    'Facility Management': [
      'Facility cleaning',
      'Locker management',
      'Shower maintenance',
      'Safety monitoring',
    ],
    'Administrative Support': [
      'Appointment scheduling',
      'Record keeping',
      'Billing assistance',
      'Inventory management',
    ],
  },
};
