Map<String, Map<String, String>> shopCategories = {
  'Grocery': {
    'Fruits':
        'https://w7.pngwing.com/pngs/669/488/png-transparent-shopping-cart-fruit-vegetable-supermarket-shopping-cart-natural-foods-food-supermarket-thumbnail.png',
    'Baked':
        'https://img.freepik.com/free-vector/bakery-products-flat-composition-with-pile-baked-foods-with-wooden-basket-sweets-coffee-cup-vector-illustration_1284-81490.jpg',
    'Canned':
        'https://img.lovepik.com/png/20231129/plastic-protien-jar-3d-rendering-png-cans-tin_724047_wh860.png',
    'Beverages':
        'https://img.freepik.com/free-photo/bottles-with-colorful-cocktail-ice_144627-21737.jpg?size=626&ext=jpg&ga=GA1.1.735520172.1712275200&semt=ais',
    'Candies':
        'https://images.creativefabrica.com/products/previews/2023/10/27/vWfI3vbJZ/2XMsm9taovAIafngUJ5iYAvqMrD-mobile.jpg',
    'Snacks':
        'https://static.vecteezy.com/system/resources/thumbnails/025/065/315/small_2x/fast-food-meal-with-ai-generated-free-png.png',
    'Frozen':
        'https://media.sketchfab.com/models/914ab4c2d96849c2b3e30c5a6495bb7c/thumbnails/99b57ef7dd1e486e8c7449dd05bebb2c/41d712f612dc456db6453304478e1703.jpeg',
    'Rice & Cereal':
        'https://w7.pngwing.com/pngs/212/294/png-transparent-whole-grain-whole-food-cereal-whole-wheat-bread-brown-rice-rice-natural-foods-food-eating.png',
  },
  'Pharmacies': {
    'Clincial Medicines': '',
    'Dermatology': '',
    'Oncology': '',
    'Emergency Medicines': '',
    'Pain Killers': '',
    'Hematology': '',
    'Cardiology': '',
    'Endocrinology': '',
    'Hepatology': '',
    'Immunology': '',
    'Nephrology': '',
    'Internal Medicines': '',
    'Medical Equipments': '',
  },
  'Electronics': {
    'Mobile & Tabs': '',
    'Televisions': '',
    'Headphones': '',
    'Cameras': '',
    'Gaming': '',
    'Air Conditioners': '',
    'Refrigerators': '',
    'Washing Machines': '',
    'Speakers': '',
    'Screen Protectors': '',
    'Power Banks': '',
    'Software': '',
    'Laptops': '',
    'Drives & Storage': '',
    'Printers & Ink': '',
    'Desktop': '',
    'Home Appliances': '',
  },
  'Clothing and Apparel': {
    'T Shirt': '',
    'Polos': '',
    'Shirts': '',
    'Jeans': '',
    'Innerwear': '',
    'Sunglasses': '',
    'Watches': '',
    'Shoes': '',
    'Sportswear': '',
    'Wallets': '',
    'Western': '',
    'Ethnic': '',
    'Sandals': '',
  },
  'Restaurant & Cafes': {
    'Appetizers': '',
    'Soups': '',
    'Salads': '',
    'Sides': '',
    'Desserts': '',
    'Beverages': '',
    'Dips': '',
    'Western': '',
    'Chinese': '',
    'Indian': '',
  },
  'Beauty and Cosmetics': {
    'Skin Care': '',
    'Hair Care': '',
    'Nail Care': '',
    'Oral Hygiene': '',
    'Lipsticks': '',
    'Eye Shadow & Eye Liners': '',
    'Tattoos': '',
  },
  'Furniture': {
    'Chairs': '',
    'Benches': '',
    'Beds': '',
    'Couches': '',
    'Toddlers': '',
    'Tables': '',
    'Desks': '',
    'Shelfs': '',
    'Cupboards': '',
    'Racks': '',
  },
  'Jewelry': {
    'Body Piercings': '',
    'Bracelets': '',
    'Brooches': '',
    'Necklaces': '',
    'Rings': '',
    'Luxury Watches': '',
    'Gem Stones': '',
    'Pendants': '',
  },
  'Decorations': {
    'Clocks': '',
    'Mirrors': '',
    'Frames': '',
    'Vases': '',
    'Rugs': '',
    'Cushions': '',
    'Paintings': '',
    'Wall Stickers': '',
    'Screens': '',
    'Room Dividers': '',
    'Curtains': '',
    'Plant Pots': '',
    'Flower Pot Holder': '',
    'Vertical Garden': '',
  },
  'Bookstores and Stationery': {
    'Fiction Book': '',
    'Non Fiction Books': '',
    'Educational Books': '',
    'Necessary': '',
    'Activity Book': '',
    'Coloring': '',
    'Presentation Goods': '',
  },
  'Building Materials and Hardware': {
    'Steel': '',
    'Cement': '',
    'Concrete': '',
    'Wires': '',
    'Wood': '',
    'Stone': '',
    'Bricks': '',
  },
  'Automobile Parts and Accessories': {
    'Brakes': '',
    'Battery': '',
    'Axles': '',
    'Transmittors': '',
    'Clutch': '',
    'Lights': '',
    'Engines': '',
    'Suspension': '',
    'Seat Covers': '',
    'Helmets & Gloves': '',
  },
  'Gifts and Novelty': {
    'Mugs': '',
    'Frames': '',
    'Chocolates': '',
    'Accessories': '',
    'Gift Hampers': '',
    'Handcrafted': '',
    'Pet Gifts': '',
    'Religious': '',
  },
  'Toys': {
    'STEM Toys': '',
    'Stuffed Toys': '',
    'Mechanical Toys': '',
    'Puzzles': '',
    'Educational Toys': '',
    'Vehicles': '',
    'Dolls': '',
    'Musical Toys': '',
    'Baby Toys': '',
    'Ridables': '',
    'Radio Controlled': '',
    'Animal Toys': '',
    'Cards': '',
    'Action': '',
    'Construction Toys': '',
    'Creative Toys': '',
    'Blocks & Bricks': '',
    'Home Sets': '',
    'Spinners': '',
    'Robots': '',
  },
  'Sports Goods': {
    'Cricket': '',
    'Badminton': '',
    'Roller Skates': '',
    'Hockey': '',
    'Bowling': '',
    'Baseball': '',
    'Rugby': '',
    'Darts & Targets': '',
    'Football': '',
    'Sportswear': '',
    'Balls': '',
  },
  'Agriculture and Farm Supply': {
    'Irrigation Machines': '',
    'Seeds': '',
    'Fertilizers': '',
    'Farming Tools': '',
    'Soil': '',
    'Ploughs': '',
    'Planters': '',
    'Containers': '',
    'Harvester': '',
    'Big Machines': '',
  },
};
